In [4]:
import pandas as pd

In [5]:
file1 = pd.read_csv('file1.csv')

In [6]:
file2 = pd.read_csv('file2.csv')

In [7]:
file3 = pd.read_csv('file3.csv')

In [8]:
file1.shape

(4008, 11)

In [9]:
file2.shape

(996, 11)

In [10]:
file3.shape

(7070, 11)

In [11]:
file1.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [12]:
file2.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Total Claim Amount', 'Policy Type', 'Vehicle Class'],
      dtype='object')

In [13]:
file3.columns

Index(['Customer', 'State', 'Customer Lifetime Value', 'Education', 'Gender',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Total Claim Amount', 'Vehicle Class'],
      dtype='object')

In [14]:
cols = []
for i in range(len(file1.columns)):
    cols.append(file1.columns[i].lower()) # Here we use the function "lower" to swhicht the column letters to lowercase.
file1.columns = cols

In [15]:
file1.columns

Index(['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'],
      dtype='object')

In [16]:
cols = []
for i in range(len(file2.columns)):
    cols.append(file2.columns[i].lower()) # Here we use the function "lower" to swhicht the column letters to lowercase.
file2.columns = cols
file2.columns


Index(['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'total claim amount', 'policy type', 'vehicle class'],
      dtype='object')

In [17]:
cols = []
for i in range(len(file3.columns)):
    cols.append(file3.columns[i].lower()) # Here we use the function "lower" to swhicht the column letters to lowercase.
file3.columns = cols

In [18]:
file1 = file1[['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints', 'total claim amount','policy type' , 'vehicle class' ]]

In [19]:
file3.columns


Index(['customer', 'state', 'customer lifetime value', 'education', 'gender',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'total claim amount', 'vehicle class'],
      dtype='object')

In [20]:
file1 = file1.rename(columns={ 'st':'state'})


In [21]:
file1.columns ==file3.columns

array([ True,  True, False,  True, False,  True,  True,  True, False,
       False,  True])

In [22]:
file3 = file3[['customer', 'state', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints', 'total claim amount','policy type' , 'vehicle class' ]]

In [23]:
file1.columns == file2.columns

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [24]:
file2.columns == file3.columns

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [25]:
file2.columns

Index(['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'total claim amount', 'policy type', 'vehicle class'],
      dtype='object')

In [26]:
file2= file2.rename(columns={ 'st':'state'})


In [27]:
file2.columns == file3.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [28]:
column_names = file1.columns
df = pd.DataFrame(columns=column_names)
df =pd.concat([data,file1,file2,file3],axis = 0)
df.shape

NameError: name 'data' is not defined

In [29]:
df._get_numeric_data()

Empty DataFrame
Columns: []
Index: []

In [30]:
import numpy as np


In [31]:
df.select_dtypes(np.object)


Empty DataFrame
Columns: [customer, state, gender, education, customer lifetime value, income, monthly premium auto, number of open complaints, total claim amount, policy type, vehicle class]
Index: []

In [32]:
file1.head()

customer       state gender             education customer lifetime value  \
0  RB50392  Washington    NaN                Master                     NaN   
1  QZ44356     Arizona      F              Bachelor              697953.59%   
2  AI49188      Nevada      F              Bachelor             1288743.17%   
3  WW63253  California      M              Bachelor              764586.18%   
4  GA49547  Washington      M  High School or Below              536307.65%   

    income  monthly premium auto number of open complaints  \
0      0.0                1000.0                    1/0/00   
1      0.0                  94.0                    1/0/00   
2  48767.0                 108.0                    1/0/00   
3      0.0                 106.0                    1/0/00   
4  36357.0                  68.0                    1/0/00   

   total claim amount     policy type  vehicle class  
0            2.704934   Personal Auto  Four-Door Car  
1         1131.464935   Personal Auto  Four-Door Car  
2          566.472247   Personal Auto   Two-Door Car  
3          529.881344  Corporate Auto            SUV  
4           17.269323   Personal Auto  Four-Door Car

In [33]:
df['customer lifetime value'].replace({'%':''},regex=True)

Series([], Name: customer lifetime value, dtype: object)

In [34]:
df['customer lifetime value'] = (df['customer lifetime value'], errors='coerce')

SyntaxError: invalid syntax (<ipython-input-34-1da18440d12b>, line 1)

In [73]:
df = df.drop_duplicates() 

In [74]:
data.drop(['education','number of open complaints'], axis =1, inplace = True)

In [97]:
df['customer lifetime value'] = df['customer lifetime value'] * 100
    

In [91]:
mean = np.mean(df['income'])

In [105]:
df['income'].fillna(mean)

0           0.0
1           0.0
2       48767.0
3           0.0
4       36357.0
         ...   
7065    71941.0
7066    21604.0
7067        0.0
7068    21941.0
7069        0.0
Name: income, Length: 9135, dtype: float64

In [104]:
df.head()

customer       state gender             education  customer lifetime value  \
0  RB50392  Washington    NaN                Master                      NaN   
1  QZ44356     Arizona      F              Bachelor                      NaN   
2  AI49188      Nevada      F              Bachelor                      NaN   
3  WW63253  California      M              Bachelor                      NaN   
4  GA49547  Washington      M  High School or Below                      NaN   

    income  monthly premium auto number of open complaints  \
0      0.0                1000.0                    1/0/00   
1      0.0                  94.0                    1/0/00   
2  48767.0                 108.0                    1/0/00   
3      0.0                 106.0                    1/0/00   
4  36357.0                  68.0                    1/0/00   

   total claim amount     policy type  vehicle class  
0            2.704934   Personal Auto  Four-Door Car  
1         1131.464935   Personal Auto  Four-Door Car  
2          566.472247   Personal Auto   Two-Door Car  
3          529.881344  Corporate Auto            SUV  
4           17.269323   Personal Auto  Four-Door Car

In [95]:
print(mean)

37824.84705495949


In [107]:
filtered = df[df['income']<=0]

In [109]:
mean = np.mean(df['income'])

In [110]:
df['come'] = df['income'].fillna(mean)

In [111]:
df.head()

customer       state gender             education  customer lifetime value  \
0  RB50392  Washington    NaN                Master                      NaN   
1  QZ44356     Arizona      F              Bachelor                      NaN   
2  AI49188      Nevada      F              Bachelor                      NaN   
3  WW63253  California      M              Bachelor                      NaN   
4  GA49547  Washington      M  High School or Below                      NaN   

    income  monthly premium auto number of open complaints  \
0      0.0                1000.0                    1/0/00   
1      0.0                  94.0                    1/0/00   
2  48767.0                 108.0                    1/0/00   
3      0.0                 106.0                    1/0/00   
4  36357.0                  68.0                    1/0/00   

   total claim amount     policy type  vehicle class     come  
0            2.704934   Personal Auto  Four-Door Car      0.0  
1         1131.464935   Personal Auto  Four-Door Car      0.0  
2          566.472247   Personal Auto   Two-Door Car  48767.0  
3          529.881344  Corporate Auto            SUV      0.0  
4           17.269323   Personal Auto  Four-Door Car  36357.0

customer lifetime value   income  monthly premium auto  \
0                         NaN      0.0                1000.0   
1                         NaN      0.0                  94.0   
2                         NaN  48767.0                 108.0   
3                         NaN      0.0                 106.0   
4                         NaN  36357.0                  68.0   
...                       ...      ...                   ...   
7065             2.340599e+08  71941.0                  73.0   
7066             3.096511e+07  21604.0                  79.0   
7067             8.163890e+07      0.0                  85.0   
7068             7.524442e+07  21941.0                  96.0   
7069             2.611837e+07      0.0                  77.0   

      total claim amount     come  
0               2.704934      0.0  
1            1131.464935      0.0  
2             566.472247  48767.0  
3             529.881344      0.0  
4              17.269323  36357.0  
...                  ...      ...  
7065          198.234764  71941.0  
7066          379.200000  21604.0  
7067          790.784983      0.0  
7068          691.200000  21941.0  
7069          369.600000      0.0  

[9135 rows x 5 columns]